name: swatch
description: Slurm job monitoring application

# Publishing information
publish_to: 'none'

# App version
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  http: ^0.13.5
  shared_preferences: ^2.0.15  # Use this for all storage
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# Flutter configuration
flutter:
  uses-material-design: true