name: swatch
description: Slurm job monitoring application

# Publishing information
publish_to: 'none'

# App version
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4  # Downgraded to be compatible with http ^0.13.5
  provider: ^6.0.5
  http: ^0.13.5
  shared_preferences: ^2.0.15  # Use this for all storage
  cupertino_icons: ^1.0.5
  flutter_acrylic: ^1.1.3  # For frosted glass effects on desktop
  clipboard: ^0.1.3  # For copy functionality
  graphview: ^1.2.0  # Add this line for graph visualization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# Flutter configuration
flutter:
  uses-material-design: true
  # Comment out assets until you have the actual files
  # assets:
  #   - assets/images/pattern_light.png
  #   - assets/images/pattern_dark.png